sudo: false
language: python
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
  - $HOME/.cache/pip # python packages


before_install:
- rvm install 2.4.1
- openssl aes-256-cbc -K $encrypted_d44857a9a818_key -iv $encrypted_d44857a9a818_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:PyNorte/pyconamazonia2017-site.git
- git fetch origin -f gh-pages:gh-pages

install:
  - gem install sass
  - npm install gulp gulp-uglify gulp-concat gulp-sass
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
#  tenta construir o site, vai falhar caso haja algum erro
  - make publish

deploy:
  provider: script
  script: make github ping
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = false

